apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: <password>
      admin_user: <username>
  route:
    metadata: {}
    spec:
      port:
        targetPort: grafana
      tls:
        termination: edge
      to:
        kind: Service
        name: grafana-service
        weight: 100
      wildcardPolicy: None
  version: 10.4.3
