{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts Dashboard",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{label_node_role_kubernetes_io!=\"worker\"})"
    }
   ]
  },
  {
   "title": "Allocatable Cores",
   "type": "stat",
   "description": "Excludes control plane",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{label_node_role_kubernetes_io!=\"worker\"})"
    }
   ]
  },
  {
   "title": "Cluster Http Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Req" }
   ],
   "targets": [
    {
     "expr": "code:cluster:ingress_http_request_count:rate5m:sum",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "graph",
   "description": "Detect NotReady, DiskPressure, MemoryPressure, and PIDPressure conditions on kubelet for Schedulable nodes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"Ready\", status!=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "NotReady: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "DiskPressure: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "MemoryPressure: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "PIDPressure: {{node}}"
    }
   ]
  },
  {
   "title": "Application Projects",
   "type": "stat",
   "description": "Excludes infrastructure namespaces",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{phase='Active',namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "stat",
   "description": "Excludes control plane",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum{label_node_role_kubernetes_io!=\"worker\"})"
    }
   ]
  },
  {
   "title": "Application Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\",namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Allocated App Storage",
   "type": "stat",
   "description": "Persistent volume claims for applications",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes {namespace!~\"(default|kube|openshift).*\"})/1e+9"
    }
   ]
  },
  {
   "title": "Utilization by Tier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization by Master Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((instance:node_load1_per_cpu:ratio) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) and sum by (node) (cluster:worker_nodes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Compute Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((instance:node_load1_per_cpu:ratio) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) unless sum by (node) (cluster:worker_nodes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Infra Namespace",
   "type": "graph",
   "description": "Display top 20",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (namespace:container_cpu_usage:sum{namespace=~\"(openshift).*\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App Namespace",
   "type": "graph",
   "description": "Display top 20",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (namespace:container_cpu_usage:sum{namespace!~\"(openshift).*\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Master Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((instance:node_memory_utilisation:ratio) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) and sum by (node) (cluster:worker_nodes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Compute Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((instance:node_memory_utilisation:ratio) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) unless sum by (node) (cluster:worker_nodes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Infra Namespace",
   "type": "graph",
   "description": "Display top 20",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (namespace:container_memory_usage_bytes:sum{namespace=~\"(openshift).*\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage by App Namespace",
   "type": "graph",
   "description": "Display top 20",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (namespace:container_memory_usage_bytes:sum{namespace!~\"(openshift).*\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Throughput by Master Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((irate(node_network_receive_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) and (sum by (node) (cluster:worker_nodes))",
     "legendFormat": "in : {{node}}"
    },
    {
     "expr": "sum by (node) ((irate(node_network_transmit_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) and (sum by (node) (cluster:worker_nodes))",
     "legendFormat": "out : {{node}}"
    }
   ]
  },
  {
   "title": "Network Throughput by Compute Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((irate(node_network_receive_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) unless (sum by (node) (cluster:worker_nodes))",
     "legendFormat": "in : {{node}}"
    },
    {
     "expr": "sum by (node) ((irate(node_network_transmit_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) unless (sum by (node) (cluster:worker_nodes))",
     "legendFormat": "out: {{node}}"
    }
   ]
  },
  {
   "title": "Error Bytes by Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (rate(node_network_receive_errs_total{device!~\"veth.+\",job=\"node-exporter\"}[2m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "receive: {{node}}"
    },
    {
     "expr": "sum by (node) (rate(node_network_transmit_errs_total{device!~\"veth.+\",job=\"node-exporter\"}[2m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "transmit: {{node}}"
    }
   ]
  },
  {
   "title": "CoreDNS Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(coredns_cache_hits_total[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(coredns_cache_misses_total[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes by Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info) by (kernel_version)",
     "legendFormat": "kernel: {{kernel_version}}"
    },
    {
     "expr": "sum(kube_node_info) by (container_runtime_version)",
     "legendFormat": "runtime: {{container_runtime_version}}"
    },
    {
     "expr": "sum(kube_node_info) by (kubelet_version)",
     "legendFormat": "kubernetes: {{kubelet_version}}"
    }
   ]
  },
  {
   "title": "Operators by Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (condition, version) ((cluster_operator_conditions) * on (name) group_left(version) (cluster_operator_up))",
     "legendFormat": "version: {{version}} / {{condition}}"
    }
   ]
  },
  {
   "title": "NetFilter Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(node_nf_conntrack_entries) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node NTP Offset",
   "type": "graph",
   "description": "Only display nodes with large NTP offset",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "Display busiest device (highest I/O) for each server",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (irate(node_disk_io_time_seconds_total{job=\"node-exporter\",device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+\"}[1m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filesystem Disk Usage",
   "type": "graph",
   "description": "Mountpoints > 50% disk space used",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (instance, namespace, pod, device) ((node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint!=\"/boot\"}\n- node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint!=\"/boot\"})\n/ node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", mountpoint!=\"/boot\"})* on (namespace, pod) group_left(node)\nnode_namespace_pod:kube_pod_info:",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Processor Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total[5m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "context_switches: {{node}}"
    },
    {
     "expr": "irate(node_intr_total[5m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:",
     "legendFormat": "hw_interrupts: {{node}}"
    }
   ]
  }
 ]
}