---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-csi   ### remove this line to test the default StorageClass
