---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io   
parameters:
  server: <>nfs-server> ### NFS server's IP/FQDN
  share:  <dir-exported> ### NFS server's exported directory
reclaimPolicy: Delete
volumeBindingMode: Immediate
